// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgdhedzxeznsevlnnhvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZGhlZHp4ZXpuc2V2bG5uaHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDkwODksImV4cCI6MjA3MjIyNTA4OX0.zkb9pEir6RNL4p_l6kFUB-lnyToZe_npQpw3135OS2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});